import { Drive } from './types';

// Windows XP-style file system structure
export const windowsXPFileSystem: Drive = {
  id: 'c-drive',
  name: 'Local Disk (C:)',
  type: 'drive',
  letter: 'C',
  path: 'C:\\',
  icon: 'My Computer.png',
  totalSpace: 40000000000, // 40GB
  freeSpace: 25000000000, // 25GB free
  dateCreated: new Date('2001-10-25'),
  dateModified: new Date(),
  children: [
    {
      id: 'documents-and-settings',
      name: 'Documents and Settings',
      type: 'folder',
      path: 'C:\\Documents and Settings',
      icon: 'Folder Closed.png',
      parentId: 'c-drive',
      dateCreated: new Date('2001-10-25'),
      dateModified: new Date(),
      children: [
        {
          id: 'administrator',
          name: 'Administrator',
          type: 'folder',
          path: 'C:\\Documents and Settings\\Administrator',
          icon: 'Folder Closed.png',
          parentId: 'documents-and-settings',
          dateCreated: new Date('2001-10-25'),
          dateModified: new Date(),
          children: [
            {
              id: 'desktop-folder',
              name: 'Desktop',
              type: 'folder',
              path: 'C:\\Documents and Settings\\Administrator\\Desktop',
              icon: 'Desktop.png',
              parentId: 'administrator',
              dateCreated: new Date('2001-10-25'),
              dateModified: new Date(),
              children: [
                {
                  id: 'my-computer-shortcut',
                  name: 'My Computer',
                  type: 'shortcut',
                  path: 'C:\\Documents and Settings\\Administrator\\Desktop\\My Computer.lnk',
                  icon: 'My Computer.png',
                  parentId: 'desktop-folder',
                  targetId: 'my-computer',
                  targetPath: 'My Computer',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                },
                {
                  id: 'recycle-bin-shortcut',
                  name: 'Recycle Bin',
                  type: 'shortcut',
                  path: 'C:\\Documents and Settings\\Administrator\\Desktop\\Recycle Bin.lnk',
                  icon: 'Recycle Bin (empty).png',
                  parentId: 'desktop-folder',
                  targetId: 'recycle-bin',
                  targetPath: 'Recycle Bin',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                },
                {
                  id: 'my-documents-shortcut',
                  name: 'My Documents',
                  type: 'shortcut',
                  path: 'C:\\Documents and Settings\\Administrator\\Desktop\\My Documents.lnk',
                  icon: 'My Documents.png',
                  parentId: 'desktop-folder',
                  targetId: 'my-documents',
                  targetPath:
                    'C:\\Documents and Settings\\Administrator\\My Documents',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                },
                {
                  id: 'internet-explorer-shortcut',
                  name: 'Internet Explorer',
                  type: 'shortcut',
                  path: 'C:\\Documents and Settings\\Administrator\\Desktop\\Internet Explorer.lnk',
                  icon: 'Internet Explorer.png',
                  parentId: 'desktop-folder',
                  targetId: 'internet-explorer',
                  targetPath:
                    'C:\\Program Files\\Internet Explorer\\iexplore.exe',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                },
                {
                  id: 'sample-document',
                  name: 'New Text Document.txt',
                  type: 'file',
                  path: 'C:\\Documents and Settings\\Administrator\\Desktop\\New Text Document.txt',
                  icon: 'Notepad.png',
                  parentId: 'desktop-folder',
                  content: 'Welcome to Windows XP!',
                  extension: 'txt',
                  size: 21,
                  dateCreated: new Date(),
                  dateModified: new Date(),
                },
              ],
            },
            {
              id: 'my-documents',
              name: 'My Documents',
              type: 'folder',
              path: 'C:\\Documents and Settings\\Administrator\\My Documents',
              icon: 'My Documents.png',
              parentId: 'administrator',
              dateCreated: new Date('2001-10-25'),
              dateModified: new Date(),
              children: [
                {
                  id: 'my-pictures',
                  name: 'My Pictures',
                  type: 'folder',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\My Pictures',
                  icon: 'My Pictures.png',
                  parentId: 'my-documents',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                  children: [
                    {
                      id: 'sample-photos',
                      name: 'Sample Pictures',
                      type: 'folder',
                      path: 'C:\\Documents and Settings\\Administrator\\My Documents\\My Pictures\\Sample Pictures',
                      icon: 'Folder Closed.png',
                      parentId: 'my-pictures',
                      dateCreated: new Date('2001-10-25'),
                      dateModified: new Date(),
                      children: [],
                    },
                  ],
                },
                {
                  id: 'my-music',
                  name: 'My Music',
                  type: 'folder',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\My Music',
                  icon: 'My Music.png',
                  parentId: 'my-documents',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                  children: [
                    {
                      id: 'sample-music',
                      name: 'Sample Music',
                      type: 'folder',
                      path: 'C:\\Documents and Settings\\Administrator\\My Documents\\My Music\\Sample Music',
                      icon: 'Folder Closed.png',
                      parentId: 'my-music',
                      dateCreated: new Date('2001-10-25'),
                      dateModified: new Date(),
                      children: [],
                    },
                  ],
                },
                {
                  id: 'my-videos',
                  name: 'My Videos',
                  type: 'folder',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\My Videos',
                  icon: 'My Videos.png',
                  parentId: 'my-documents',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                  children: [],
                },
                {
                  id: 'my-received-files',
                  name: 'My Received Files',
                  type: 'folder',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\My Received Files',
                  icon: 'Folder Closed.png',
                  parentId: 'my-documents',
                  dateCreated: new Date('2001-10-25'),
                  dateModified: new Date(),
                  children: [],
                },
                {
                  id: 'project-files',
                  name: 'Project Files',
                  type: 'folder',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\Project Files',
                  icon: 'Folder Closed.png',
                  parentId: 'my-documents',
                  dateCreated: new Date('2025-06-28'),
                  dateModified: new Date(),
                  children: [],
                },
                {
                  id: 'work-documents',
                  name: 'Work Documents',
                  type: 'folder',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\Work Documents',
                  icon: 'Folder Closed.png',
                  parentId: 'my-documents',
                  dateCreated: new Date('2025-06-28'),
                  dateModified: new Date(),
                  children: [],
                },
                {
                  id: 'personal-files',
                  name: 'Personal Files',
                  type: 'folder',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\Personal Files',
                  icon: 'Folder Closed.png',
                  parentId: 'my-documents',
                  dateCreated: new Date('2025-06-28'),
                  dateModified: new Date(),
                  children: [],
                },
                {
                  id: 'readme-doc',
                  name: 'ReadMe.txt',
                  type: 'file',
                  path: 'C:\\Documents and Settings\\Administrator\\My Documents\\ReadMe.txt',
                  icon: 'Notepad.png',
                  parentId: 'my-documents',
                  content:
                    'Welcome to your My Documents folder! This is where you can store your personal files and documents.',
                  extension: 'txt',
                  size: 95,
                  dateCreated: new Date('2025-06-28'),
                  dateModified: new Date(),
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
